# Generated by Django 2.2.2 on 2019-06-16 17:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190616_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=stdimage.models.StdImageField(upload_to='media/post_images'),
        ),
    ]
