# Generated by Django 2.2.2 on 2019-06-16 17:19

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190616_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to='media/post_images'),
        ),
    ]
