# Generated by Django 2.2.2 on 2019-08-08 05:58

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Class Notes', 'Class Notes'), ('MTT papers', 'MTT papers'), ('RTU papers', 'RTU papers'), ('Coding related stuff', 'Coding related stuff'), ('Book', 'Book'), ('magazines', 'magazines'), ('others', 'others')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
