# Generated by Django 2.2.2 on 2019-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0002_auto_20190808_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Class Notes', 'Class Notes'), ('MTT papers', 'MTT papers'), ('RTU papers', 'RTU papers'), ('Coding related stuff', 'Coding related stuff'), ('Book', 'Book'), ('magazines', 'magazines'), ('others', 'others')], max_length=30, null=True),
        ),
    ]
