# Generated by Django 2.2.2 on 2019-12-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0004_auto_20191224_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='thumbnail',
        ),
    ]
