# Generated by Django 2.2.2 on 2019-06-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower',
            new_name='follows',
        ),
    ]
