# Generated by Django 2.2.2 on 2019-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_auto_20190720_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='posted_by',
            field=models.TextField(max_length=20),
        ),
    ]
