# Generated by Django 2.2.2 on 2019-07-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_auto_20190720_0516'),
        ('qanda', '0003_auto_20190720_1027'),
    ]

    operations = [
    ]
